name: node-js-getting-started

on:
  push:
    branches:
      - main
      
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    #needs: test-unit
   # if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      # possibly setup node action here...
      # possibly cache of node modules action here...
      # build steps here...
      - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          email: ${{secrets.HEROKU_EMAIL}}
          app_name: na-new-app
          heroku_branch: "master"
          subfolder: ""
